name: ttbar_particle_unfolding_weighted

network:
  hidden_dim: 32
  dropout: 0.0
  transformer_heads: 4
  transformer_expansion: 2
  skip_connection_type: GRU
  denoising_expansion: 2

  num_denoising_layers: 8
  num_multiplicity_layers: 4
  num_detector_encoder_layers: 8
  num_particle_encoder_layers: 6
  num_particle_decoder_layers: 6
  num_linear_layers: 1

  ordered_detector_encoder: false
  ordered_particle_encoder: false
  ordered_denoising_network: false

  conditional_particle_encoder: false
  conditional_particle_decoder: false

  normalized_particle_encoder: true
  deterministic_particle_encoder: true
  coupled_diffusion_particle_decoder: true

noise_schedule:
  noise_schedule: ConditionalNetwork
  weighting: Unit

  initial_gamma_min: -5.0
  initial_gamma_max: 5.0

  limit_gamma_min: -12.0
  limit_gamma_max: 12.0

training:
  reconstruction_loss_scale: 2.0
  latent_prior_loss_scale: 0.0
  diffusion_prior_loss_scale: 1.0
  norm_prior_loss_scale: 0.0
  multiplicity_loss_scale: 1.0
  consistency_loss_scale: 0.0
  
  seed: 0
  batch_size: 64

  learning_rate: 0.001
  learning_rate_minimum: 0.000001
  learning_rate_decay: 0.95

  gradient_clipping: 1.0
  unconditional_probability: 0.1

  warmup_steps: 1000
  cosine_steps: 100000
  training_steps: 10000000
