channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.11
  - numba
  - numpy

  - jupyterlab
  - matplotlib
  - seaborn

  - pip
  - pip:
      - tensorflow
      - tensorflow-datasets
      - tensorflow-probability
      - tf_keras
      - vector

      - omegaconf
      - wandb
      - diffusers
      
      - jax[cuda12]
      - flax
      - optax
      - diffrax
      - orbax-checkpoint