name: ???

network:
  hidden_dim: 64
  dropout: 0.1
  transformer_heads: 4
  transformer_expansion: 2
  skip_connection_type: gru
  denoising_expansion: 1
  num_denoising_layers: 8
  num_multiplicity_layers: 2
  num_detector_encoder_layers: 8
  num_particle_encoder_layers: 8
  num_particle_decoder_layers: 8
  num_linear_layers: 2
  ordered_detector_encoder: true
  ordered_particle_encoder: true
  ordered_denoising_network: true
  conditional_particle_encoder: true
  conditional_particle_decoder: true
  normalized_particle_encoder: true
  deterministic_particle_encoder: false

noise_schedule:
  noise_schedule: cosine
  weighting: sigmoid

training:
  reconstruction_loss_scale: 1.0
  latent_prior_loss_scale: 0.0
  diffusion_prior_loss_scale: 0.0
  norm_prior_loss_scale: 0.0
  multiplicity_loss_scale: 0.0
  event_loss_weight: 1.0
  seed: 0
  batch_size: 1024
  learning_rate: 0.001
  gradient_clipping: 1.0
  unconditional_probability: 0.1
  warmup_steps: 1000
  cosine_steps: 100000
  training_steps: 1000000
