name: ttbar_particle_percentile_pretrain
base: config/ttbar_final_base.yaml

noise_schedule:
  limit_gamma_min: -5.0
  limit_gamma_max: 5.0

training:
  diffusion_loss_scale: 0.0
  reconstruction_loss_scale: 1.0
  latent_prior_loss_scale: 0.0
  diffusion_prior_loss_scale: 0.0
  norm_prior_loss_scale: 0.0
  multiplicity_loss_scale: 1.0
  consistency_loss_scale: 0.0
