name: zjets_small_main
base: config/zjets.medium.base.yaml

noise_schedule:
  limit_gamma_min: -12.0
  limit_gamma_max: 12.0

training:
  diffusion_loss_scale: 1.0
  reconstruction_loss_scale: 1.0
  latent_prior_loss_scale: 0.01
  diffusion_prior_loss_scale: 1.0
  norm_prior_loss_scale: 0.0
  multiplicity_loss_scale: 1.0

  consistency_loss_scale: 0.0001
  consistency_loss_type: ZJetsAbsoluteLog
