name: zjets_small_main
base: config/zjets.small.base.yaml
network:
  hidden_dim: 8
  dropout: 0.0
  transformer_heads: 1
  transformer_expansion: 2
  skip_connection_type: GRU
  denoising_expansion: 3
  num_denoising_layers: 6
  num_multiplicity_layers: 2
  num_detector_encoder_layers: 6
  num_particle_encoder_layers: 6
  num_particle_decoder_layers: 6
  num_linear_layers: 0
  ordered_detector_encoder: false
  ordered_particle_encoder: false
  ordered_denoising_network: true
  conditional_particle_encoder: false
  conditional_particle_decoder: false
  normalized_particle_encoder: false
  deterministic_particle_encoder: true
  coupled_diffusion_particle_decoder: true
  discrete_multiplicity_predictor: false
noise_schedule:
  noise_schedule: Network
  weighting: EDM
  sigmoid_weighting_offset: 2.0
  initial_gamma_min: -3.0
  initial_gamma_max: 3.0
  limit_gamma_max: 12.0
  limit_gamma_min: -12.0
  hidden_dim: 1024
  output_dim: 1
  conditioning_dim: 128
training:
  diffusion_loss_scale: 1.0
  reconstruction_loss_scale: 1.0
  latent_prior_loss_scale: 0.1
  diffusion_prior_loss_scale: 1.0
  norm_prior_loss_scale: 0.0
  multiplicity_loss_scale: 1.0
  consistency_loss_scale: 0.0
  consistency_loss_type: Identity
  seed: 0
  batch_size: 32
  gradient_clipping: 1.0
  unconditional_probability: 0.0
  warmup_steps: 1000
  cosine_steps: 100000
  training_steps: 10000000
  learning_rate: 0.001
  learning_rate_minimum: 1.0e-06
  learning_rate_decay: 0.95
  log_interval: 50
  checkpoint_interval: 1000
  checkpoint_mask:
  - lvd_state.params['detector_encoder']
  - lvd_state.params['particle_encoder']
  - lvd_state.params['particle_decoder']
  - lvd_state.params['multiplicity_predictor']
  negative_checkpoint_mask: false
dataset:
  detector_vector_dim: 3
  detector_event_dim: 8
  particle_vector_dim: 3
  particle_event_dim: 8
  num_particle_types: 14
